---
- name: Install CUDA, cuDNN, TensorFlow in Conda environment
  hosts: all
  become: yes

  tasks:
    - name: Activate the 'test' Conda environment
      shell: "/root/miniconda/bin/activate test"
      args:
        executable: /bin/bash
      become_user: root
      environment:
        PATH: "/root/miniconda/bin:$PATH"
      register: conda_activation_result
      changed_when: false

    - name: Install CUDA Toolkit in 'test' environment
      command: /root/miniconda/bin/conda install -n test -c conda-forge cudatoolkit=11.8.0 -y
      become_user: root
      become: yes

    - name: Install pip
      package:
        name: python3-pip
        state: present
      become_user: root
      become: yes

    - name: Install cuDNN using pip
      pip:
        name: nvidia-cudnn-cu11==8.6.0.163
      become_user: root
      become: yes

    - name: Install TensorFlow in 'test' environment
      command: /root/miniconda/bin/conda install -n test tensorflow -y
      become_user: root
      become: yes

    - name: Print TensorFlow version
      command: /root/miniconda/envs/test/bin/python -c "import tensorflow as tf; print('TensorFlow version:', tf.__version__)"
      register: tf_version_output
      become_user: root
      become: yes

    - name: Display TensorFlow version
      debug:
        var: tf_version_output.stdout_lines
      become_user: root
      become: yes
