---
- name: Install and Configure Environment
  hosts: all
  become: yes

  tasks:
    # First playbook tasks (CUDA, cuDNN, TensorFlow)
    - name: Activate the 'test' Conda environment
      shell: "/root/miniconda/bin/activate test"
      args:
        executable: /bin/bash
      become_user: root
      environment:
        PATH: "/root/miniconda/bin:$PATH"
      register: conda_activation_result
      changed_when: false

    - name: Install CUDA Toolkit in 'test' environment
      command: /root/miniconda/bin/conda install -n test -c conda-forge cudatoolkit=11.8.0 -y
      become_user: root
      become: yes

    - name: Install pip
      package:
        name: python3-pip
        state: present
      become_user: root
      become: yes

    - name: Install cuDNN using pip
      pip:
        name: nvidia-cudnn-cu11==8.6.0.163
      become_user: root
      become: yes

    - name: Upgrade NumPy
      pip:
        name: numpy
        state: latest
      become_user: root
      become: yes

    - name: Install TensorFlow in 'test' environment
      command: /root/miniconda/bin/conda install -n test tensorflow==2.12.0 -y
      become_user: root
      become: yes

    # Second playbook tasks (Libraries and Verify)
    - name: Install required packages
      apt:
        name: [python3, python3-pip]
        state: latest
      become_user: root
      become: yes

    - name: Install other required packages
      command: "/root/miniconda/envs/test/bin/pip install torch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 pandas seaborn scipy scikit-learn gensim nltk xgboost"
      become_user: root
      become: yes

    - name: Install Jupyter using Conda
      pip:
        name: jupyter
        executable: /root/miniconda/envs/test/bin/pip
      become_user: root
      become: yes

    - name: Start Jupyter Lab
      command: "/root/miniconda/bin/jupyter lab --no-browser --allow-root --ip=0.0.0.0"
      async: true
      poll: 0
      environment:
        PATH: "/root/miniconda/bin:$PATH"
      become_user: root
      become: yes

    - name: Update libstdc++ to resolve compatibility issue  ## resolving errors with compatibility here
      command: "apt-get install -y libstdc++6"
      become_user: root
      become: yes

    - name: Reinstall scipy to resolve compatibility issue
      command: "/root/miniconda/envs/test/bin/pip install --force-reinstall scipy"
      become_user: root
      become: yes

    - name: Install required Python packages using pip
      pip:
        name:
          - torch
          - numpy
          - pandas
          - scikit-learn
          - gensim
          - nltk
          - xgboost
          - keras
        state: present
      become_user: root
      become: yes

    - name: Install compatible versions of required libraries    ### compatibility add-ons
      pip:
        name: "{{ item.name }}=={{ item.version }}"
      loop:
        - { name: numpy, version: 1.22 }
        - { name: jax, version: 0.3.15 }  
        - { name: libclang, version: 13.0.0 }  
        - { name: tensorflow-io-gcs-filesystem, version: 0.23.1 }  
        - { name: tensorflow, version: 2.12.0 } 

    - name: Install required Python packages
      pip:
        name:
          - certifi==2023.5.7
          - charset-normalizer==3.1.0
          - click==8.1.3
          - colorama==0.4.6
          - ghp-import==2.1.0
          - idna==3.4
          - Jinja2==3.1.2
          - Markdown==3.3.7
          - MarkupSafe==2.1.3
          - mergedeep==1.3.4
          - mkdocs==1.4.3
          - mkdocs-material==9.1.17
          - mkdocs-material-extensions==1.1.1
          - packaging==23.1
          - Pygments==2.15.1
          - pymdown-extensions==10.0.1
          - python-dateutil==2.8.2
          - PyYAML==6.0
          - pyyaml_env_tag==0.1
          - regex==2023.6.3
          - requests==2.31.0
          - six==1.16.0
          - urllib3==2.0.3
          - watchdog==3.0.0

    - name: Update TensorFlow, Keras, and NumPy
      pip:
        name:
          - tensorflow
          - keras
          - numpy
        state: latest
