---
- name: Install NVIDIA GPU drivers on Linux Machine
  hosts: all
  vars:
    conda_prefix: "{{ ansible_env.HOME }}/miniconda/envs/{{ conda_env_name }}"
  become: true

  tasks:
    - name: Install GPU server
      block:
      - name: Ensure Python3 is installed
        package:
          name: python3
          state: present

      - name: Download the installation script
        get_url:
          url: https://raw.githubusercontent.com/InTensorfiers/compute-gpu-installation/main/linux/install_gpu_driver.py
          dest: /tmp/install_gpu_driver.py

      - name: Run the installation script
        command: python3 /tmp/install_gpu_driver.py
        args:
          creates: /usr/bin/nvidia-smi  # Check if nvidia-smi is already installed
        register: install_output
        ignore_errors: yes  # Ignore errors since the script might restart the VM

      - name: Verify the installation
        command: sudo nvidia-smi   # we can do this in the VM to confirm installation

    - name: Install miniconda
      block:
      - name: Include the input for the python version and the CPU architecture
        set_fact:
          cpu_arch: "{{ ansible_architecture | default('x86_64') }}"

      - name: Download Miniconda
        get_url:
          url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-{{ cpu_arch }}.sh"
          dest: "{{ ansible_env.HOME }}/miniconda.sh"

      - name: Installing Miniconda
        shell: "bash {{ ansible_env.HOME }}/miniconda.sh -b -p {{ ansible_env.HOME }}/miniconda"
        args:
          creates: "{{ ansible_env.HOME }}/miniconda"

      - name: Adding Miniconda to the system path
        lineinfile:
          path: "{{ ansible_env.HOME }}/.bashrc"
          line: 'export PATH="{{ ansible_env.HOME }}/miniconda/bin:$PATH"'
          state: present
        register: lineinfile_result
        changed_when: lineinfile_result is changed

    - name: Create conda environment with all libraries
      block:
      - name: Update conda
        command: /root/miniconda/bin/conda update -n base -c defaults conda -y

      - name: Run conda init
        command: /root/miniconda/bin/conda init

      - name: Creating Conda environment
        shell: "/root/miniconda/bin/conda create -y -n {{ conda_env_name }} python={{ python_version }}"

      - name: Activate the created Conda environment
        shell: "/root/miniconda/bin/activate {{ conda_env_name }}"

      - name: Install CUDA Toolkit in conda environment
        command: /root/miniconda/bin/conda install -n {{ conda_env_name }} -c conda-forge cudatoolkit=11.8.0 -y

      - name: Install cuDNN and tensorflow
        shell: "{{ conda_prefix }}/bin/pip install nvidia-cudnn-cu11==8.6.0.163 tensorflow==2.13.*"

      - name: Add cuDNN path into conda environment
        shell: |
          mkdir -p {{ conda_prefix }}/etc/conda/activate.d && \
          echo 'CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))' >> {{ conda_prefix }}/etc/conda/activate.d/env_vars.sh && \
          echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:{{ conda_prefix }}/lib/:$CUDNN_PATH/lib' >> {{ conda_prefix }}/etc/conda/activate.d/env_vars.sh

      - name: Install Jupyter suite in conda environment
        command: /root/miniconda/bin/conda install -n {{ conda_env_name }} -c anaconda jupyter -y

      - name: Install other essential libraries
        shell: "{{ conda_prefix }}/bin/pip install numpy pandas scikit-learn xgboost scipy matplotlib seaborn chardet"
