---
- name: Install NVIDIA GPU drivers on Linux VM
  hosts: all
  become: true

  tasks:
    - name: Install GPU server
      block:
      - name: Ensure Python3 is installed
        package:
          name: python3
          state: present

      - name: Download the installation script
        get_url:
          url: https://raw.githubusercontent.com/InTensorfiers/compute-gpu-installation/main/linux/install_gpu_driver.py
          dest: /tmp/install_gpu_driver.py

      - name: Run the installation script
        command: python3 /tmp/install_gpu_driver.py
        args:
          creates: /usr/bin/nvidia-smi  # Check if nvidia-smi is already installed
        register: install_output
        ignore_errors: yes  # Ignore errors since the script might restart the VM

      - name: Verify the installation
        command: sudo nvidia-smi   # we can do this in the VM to confirm installation

    - name: Install miniconda
      block:
      - name: Include the input for the python version and the CPU architecture
        set_fact:
          cpu_arch: "{{ ansible_architecture | default('x86_64') }}"

      - name: Download Miniconda
        get_url:
          url: "https://repo.anaconda.com/miniconda/Miniconda3-py{{ python_version | replace('.', '') }}_{{ conda_version }}-0-Linux-{{ cpu_arch }}.sh"
          dest: "{{ ansible_env.HOME }}/miniconda.sh"

      - name: Installing Miniconda
        shell: "bash {{ ansible_env.HOME }}/miniconda.sh -b -p {{ ansible_env.HOME }}/miniconda"
        args:
          creates: "{{ ansible_env.HOME }}/miniconda"

      - name: Adding Miniconda to the system path
        lineinfile:
          path: "{{ ansible_env.HOME }}/.bashrc"
          line: 'export PATH="{{ ansible_env.HOME }}/miniconda/bin:$PATH"'
          state: present
        register: lineinfile_result
        changed_when: lineinfile_result is changed

    - name: Create conda environment with cudatoolkit
      block:
      - name: Creating Conda environment
        shell: "conda create -y -n {{ conda_env_name }} python={{ python_version }}"
        environment:
          PATH: "{{ ansible_env.HOME }}/miniconda/bin:$PATH"
#
#
#    - name: Install pip dependencies
#      block:
#        ## TODO